import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdir, writeFile } from 'node:fs/promises';
import { browser, openBrowser } from '../scripts/browser-harness.mjs';
import { createPreviewServer } from '../scripts/preview-server.mjs';

test('guided first visit, constraints, optional failure, exports, customize and draft return', { skip: !browser, timeout: 60000 }, async t => {
  const calls = [];
  const repos = Array.from({ length: 8 }, (_, i) => ({ name: `r${i}`, full_name: `alice/r${i}`, description: `Project ${i}`, language: 'Rust', created_at: `${2015 + i}-01-01`, updated_at: '2026-01-01', languages: { Rust: 100 }, topics: ['tools'], stargazers_count: i }));
  const server = createPreviewServer({ fetchImpl: async url => { calls.push(url);
    if (url.includes('/search/issues')) return Response.json({ total_count: 1, items: [{ user: { login: 'alice' }, pull_request: {}, repository_url: 'https://api.github.com/repos/another-org/discovered' }] });
    if (url.includes('/search/commits')) return Response.json({ total_count: 0, items: [] });
    if (/\/repos\/(team|another-org)\/(direct|discovered)$/.test(url)) { const name = url.split('/').pop(); return Response.json({ ...repos[0], name, full_name: new URL(url).pathname.slice(7), private: false }); }
    return Response.json(url.includes('/events') || url.includes('/commits?') ? { message: 'Unavailable' } : url.includes('/languages') ? { Rust: 100 } : url.includes('/repos?') ? repos : { login: 'alice', type: 'User' }, url.includes('/events') || url.includes('/commits?') ? { status: 503 } : {}); } });
  server.listen(0, '127.0.0.1'); await once(server, 'listening'); t.after(() => new Promise(resolve => { server.close(resolve); server.closeAllConnections(); }));
  const page = await openBrowser(t, `http://127.0.0.1:${server.address().port}`);
  const { evaluate: e, waitFor: wait, cdp } = page;
  const click = async text => { await e(`[...document.querySelectorAll('#guided-setup button')].find(button => button.textContent === ${JSON.stringify(text)}).click()`); await wait(`!document.querySelector('#guided-setup').hasAttribute('aria-busy')`); };
  await wait(`document.querySelector('#open-studio')?.disabled === false`);
  assert.equal(await e(`document.documentElement.dataset.entry`), 'landing');
  assert.equal(await e(`getComputedStyle(document.querySelector('.studio-body')).display`), 'none');
  await e(`document.querySelector('#open-studio').click()`);
  const guidedButton = await e(`(async()=>{const button=document.querySelector('#start-guided-setup');button.scrollIntoView({block:'center'});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const r=button.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
  await cdp('Input.dispatchMouseEvent', { type: 'mousePressed', ...guidedButton, button: 'left', clickCount: 1 });
  await cdp('Input.dispatchMouseEvent', { type: 'mouseReleased', ...guidedButton, button: 'left', clickCount: 1 });
  assert.equal(await e(`document.documentElement.dataset.entry`), 'landing');
  assert.equal(await e(`document.activeElement.id`), 'username');
  await e(`document.querySelector('#username').value='alice'; document.querySelector('#account-form').requestSubmit()`);
  await wait(`document.documentElement.dataset.entry === 'guided' && !!document.querySelector('#guided-repository-search') && !document.querySelector('#guided-setup').hasAttribute('aria-busy')`);
  assert.equal(calls.some(url => url.includes('/events')), false);
  assert.equal(await e(`document.activeElement.tagName`), 'H2');
  await e(`document.querySelector('#guided-add-repository-name').value='team/direct'; document.querySelector('#guided-add-public-repository').click()`);
  await wait(`document.querySelector('#guided-repository-picker-list input[value="team/direct"]')?.checked`);
  await e(`document.querySelector('#guided-contribution-organization').value='team'; document.querySelector('#guided-find-contributed-repositories').click()`);
  await wait(`document.querySelector('#guided-repository-picker-list input[value="another-org/discovered"]') && !document.querySelector('#guided-find-contributed-repositories').disabled`);
  assert.ok(calls.filter(url => url.includes('/search/')).every(url => !new URL(url).searchParams.get('q').includes('org:')));
  await e(`document.querySelector('#guided-repository-picker-list input[value="another-org/discovered"]').click()`);
  await e(`document.querySelector('#guided-repository-search').value='r0'; document.querySelector('#guided-repository-search').dispatchEvent(new Event('input'))`);
  assert.equal(await e(`document.querySelectorAll('#guided-repository-picker-list input').length`), 1);

  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  assert.equal(await e(`document.documentElement.scrollWidth <= innerWidth`), true);
  await click('Continue'); await click('Continue');
  await e(`for(const input of document.querySelectorAll('#guided-setup fieldset input[type="checkbox"]')) if(input.checked) input.click()`);
  await click('Skip');
  assert.equal(await e(`document.querySelector('#guided-setup h2').textContent`), 'Show your activity?');
  assert.equal(await e(`JSON.parse(localStorage.getItem('constellation-intent-v1:alice')).topics`), null);
  await e(`document.querySelector('[name="guided-activity"][value="orbit"]').click()`); await click('Continue');
  await e(`document.querySelector('[name="guided-history"][value="3d"]').click()`); await click('Continue');
  await click('Generate my constellation');
  await wait(`document.documentElement.dataset.entry === 'result'`);
  assert.match(await e(`document.querySelector('#guided-status').textContent`), /without activity/);
  await e(`document.querySelector('#view-fullscreen').click()`);
  assert.equal(await e(`document.querySelector('#image-viewer').open`), true);
  await e(`document.querySelector('#viewer-close').click()`);
  await e(`document.querySelector('#constellation-title').value='My first universe'; document.querySelector('#save-constellation').click()`);
  const draft = () => e(`JSON.parse(localStorage.getItem('constellation-config-v1:alice')).draft`);
  const before = await draft(); assert.ok(before.includeRepos.includes('team/direct')); assert.ok(before.includeRepos.includes('another-org/discovered')); assert.equal(before.arrangement, 'temporal-stack'); assert.equal(before.contributionOrbit.enabled, false);
  await click('Generate another'); await wait(`!document.querySelector('#guided-setup').hasAttribute('aria-busy')`);
  await e(`document.querySelector('#constellation-title').value='My second universe'; document.querySelector('#save-constellation').click()`);
  const after = await draft(); assert.deepEqual(after.includeRepos, before.includeRepos); assert.deepEqual(after.languages, before.languages);
  await mkdir('.dist', { recursive: true });
  const resultShot = await cdp('Page.captureScreenshot'); await writeFile('.dist/onboarding-result-mobile.png', Buffer.from(resultShot.data, 'base64'));
  await click('Use this design'); assert.equal(await e(`document.documentElement.dataset.entry`), 'install');
  assert.equal(await e(`document.querySelector('#panel-save').hidden`), false);
  await click('Customize'); assert.equal(await e(`document.documentElement.dataset.entry`), 'studio');
  assert.equal(await e(`document.querySelectorAll('.studio-tabs [role="tab"]').length`), 6);
  await e(`[...document.querySelectorAll('.design-launcher button')].find(button => button.textContent === 'Guided setup').click()`);
  await wait(`document.documentElement.dataset.entry === 'guided' && !!document.querySelector('#guided-repository-search') && !document.querySelector('#guided-setup').hasAttribute('aria-busy')`);
  assert.deepEqual((await draft()).includeRepos, before.includeRepos, 'entering the wizard preserves the manual draft');
  await click('Open full Studio');
  assert.deepEqual((await draft()).includeRepos, before.includeRepos);

  await cdp('Page.reload'); await wait(`document.querySelector('#open-studio')?.disabled === false`);
  await e(`document.querySelector('#open-constellation-library').click()`);
  assert.equal(await e(`document.querySelectorAll('.saved-constellation-row').length`), 2);
  await e(`[...document.querySelectorAll('.saved-constellation-row')].find(row=>row.textContent.includes('My first universe')).querySelector('button').click()`);
  await wait(`document.documentElement.dataset.entry === 'result'`);
  assert.equal(await e(`document.querySelector('#constellation-title').value`), 'My first universe');
  assert.equal((await draft()).seed, before.seed);
  await e(`document.querySelector('#username').value='alice'; document.querySelector('#account-form').requestSubmit()`);
  await wait(`document.documentElement.dataset.entry === 'guided' && !!document.querySelector('#guided-repository-search') && !document.querySelector('#guided-setup').hasAttribute('aria-busy')`);
  assert.equal((await draft()).seed, before.seed, 'an existing draft does not bypass setup or get overwritten');
  assert.equal(await e(`document.querySelector('.controls').getClientRects().length`), 0);
  assert.deepEqual((await draft()).includeRepos, before.includeRepos);
  assert.deepEqual(page.errors, []);
});

test('sparse profiles skip empty questions, no-activity stays lazy, asteroids load automatically', { skip: !browser, timeout: 60000 }, async t => {
  const calls = [];
  const repo = { name: 'app', full_name: 'bob/app', private: false, language: 'Rust', languages: { Rust: 100 }, created_at: '2026-01-01', updated_at: '2026-01-01' };
  const server = createPreviewServer({ fetchImpl: async url => {
    calls.push(url);
    if (url.includes('/commits?')) return Response.json([{ sha: '1'.repeat(40), parents: [], author: { login: 'bob' }, commit: { message: 'Build app', committer: { date: '2026-09-01' } } }]);
    return Response.json(url.includes('/repos?') ? [repo] : url.includes('/repos/bob/app') ? repo : { login: 'bob', type: 'User' });
  } });
  server.listen(0, '127.0.0.1'); await once(server, 'listening'); t.after(() => new Promise(resolve => { server.close(resolve); server.closeAllConnections(); }));
  const { evaluate: e, waitFor: wait, errors } = await openBrowser(t, `http://127.0.0.1:${server.address().port}`);
  const click = async text => { await e(`[...document.querySelectorAll('#guided-setup button')].find(button => button.textContent === ${JSON.stringify(text)}).click()`); await wait(`!document.querySelector('#guided-setup').hasAttribute('aria-busy')`); };
  await wait(`document.querySelector('#open-studio')?.disabled === false`);
  await e(`document.querySelector('#username').value='bob'; document.querySelector('#account-form').requestSubmit()`);
  await wait(`document.documentElement.dataset.entry === 'guided' && !!document.querySelector('#guided-repository-search') && !document.querySelector('#guided-setup').hasAttribute('aria-busy')`);
  assert.match(await e(`document.querySelector('#guided-setup > p').textContent`), /Step 1 of 4/);
  await click('Continue'); await click('Continue');
  await e(`document.querySelector('[name="guided-activity"][value="none"]').click()`); await click('Continue'); await click('Generate my constellation');
  await wait(`document.documentElement.dataset.entry === 'result'`);
  assert.equal(calls.some(url => url.includes('/events') || url.includes('/commits?')), false);
  await click('Edit answers'); await click('Continue'); await click('None'); await click('Continue'); await click('Continue'); await click('Generate my constellation');
  await wait(`document.querySelector('#guided-status').textContent.includes('no visible projects')`);
  assert.equal(await e(`document.documentElement.dataset.entry`), 'guided');
  await click('Back'); await click('Back'); await click('All'); await click('Continue');
  await e(`document.querySelector('[name="guided-activity"][value="asteroids"]').click()`); await click('Continue'); await click('Generate my constellation');
  await wait(`document.documentElement.dataset.entry === 'result'`);
  assert.equal(calls.filter(url => url.includes('/commits?')).length, 1);
  assert.equal(calls.some(url => url.includes('/events')), false);
  assert.equal(await e(`JSON.parse(localStorage.getItem('constellation-config-v1:bob')).draft.activityEffect`), 'asteroids');
  assert.deepEqual(errors, []);
});


