import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createPreviewServer } from '../scripts/preview-server.mjs';
import { browser, openBrowser } from '../scripts/browser-harness.mjs';

test('component renders isolated config and scene properties with accessible controls', { skip: !browser, timeout: 120000 }, async t => {
  const server = createPreviewServer(); server.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(() => new Promise(resolve => { server.close(resolve); server.closeAllConnections(); }));
  const { cdp, evaluate, waitFor, errors } = await openBrowser(t, `http://127.0.0.1:${server.address().port}/examples/web-component.html`);
  await waitFor(`Boolean(document.querySelector('constellation-view')?.shadowRoot?.querySelector('main')?.constellation)`);
  assert.equal(await evaluate(`document.querySelector('constellation-view').shadowRoot.querySelectorAll('.star').length`), 3);
  assert.equal(await evaluate(`document.querySelectorAll('.star').length`), 0);
  assert.ok(await evaluate(`document.querySelector('constellation-view').shadowRoot.querySelector('[data-action=zoom-in]').getAttribute('aria-label')`));
  assert.equal(await evaluate(`(() => { const view = document.querySelector('constellation-view'); const scene = view.scene; scene.nodes[0].metadata.name = 'mutated'; return view.scene.nodes[0].metadata.name === 'mutated'; })()`), false);
  await evaluate(`const first = document.querySelector('constellation-view'); const second = document.createElement('constellation-view'); second.id = 'second'; second.scene = first.scene; document.body.append(second);`);
  assert.equal(await evaluate(`document.querySelector('#second').shadowRoot.querySelectorAll('.star').length`), 3);
  await evaluate(`document.querySelector('#second').shadowRoot.querySelector('[data-action=zoom-in]').click()`);
  assert.notDeepEqual(await evaluate(`document.querySelector('#second').shadowRoot.querySelector('main').constellation.camera`), await evaluate(`document.querySelector('#view').shadowRoot.querySelector('main').constellation.camera`));
  await evaluate(`document.querySelector('#second').setAttribute('config', '{bad-json')`);
  assert.ok(await evaluate(`document.querySelector('#second').shadowRoot.querySelector('main') !== null`), 'bad updates preserve the last good view');
  await evaluate(`window.componentEvents = []; const secondView = document.querySelector('#second'); for (const type of ['scene-change','node-select','node-hover','error']) secondView.addEventListener(type, event => window.componentEvents.push({type, detail:event.detail})); secondView.selectNode(secondView.scene.nodes[0].id, {focus:false});`);
  assert.ok(await evaluate(`document.querySelector('#second').selection.start`));
  await evaluate(`document.querySelector('#second').clearSelection(); document.querySelector('#second').fit(); document.querySelector('#second').reset();`);
  assert.equal(await evaluate(`document.querySelector('#second').selection.start`), null);
  assert.equal(await evaluate(`document.querySelector('#second').setConfig({version:6,account:'next',options:{animate:false}})`), true);
  assert.ok(await evaluate(`window.componentEvents.some(event => event.type === 'scene-change' && event.detail.scene.metadata.account === 'next')`));
  assert.equal(await evaluate(`document.querySelector('#second').loadScene({version:99})`), false);
  assert.ok(await evaluate(`window.componentEvents.some(event => event.type === 'error')`));
  await evaluate(`window.detached = document.querySelector('#second'); detached.remove(); document.body.append(detached);`);
  await waitFor(`Boolean(document.querySelector('#second').shadowRoot.querySelector('main').constellation)`);
  await evaluate(`(async()=>{ window.groupedView = document.querySelector('#view'); await groupedView.setConfig({version:7,account:'example',projectFamilies:{'sample-family':{label:'Sample Family',members:['example/compiler','example/runtime','example/studio']}}}); groupedView.semanticLevel='groups'; })()`);
  await waitFor(`Boolean(groupedView.shadowRoot.querySelector('.star[data-repo="group:user:sample-family"]'))`);
  await evaluate(`groupedView.selectNode('group:user:sample-family',{focus:false})`);
  assert.ok(await evaluate(`groupedView.shadowRoot.querySelector('[data-details]').textContent.includes('Why grouped?')`));
  await evaluate(`groupedView.shadowRoot.querySelector('[data-semantic-expand]').focus()`);
  await cdp("Input.dispatchKeyEvent", { type: "keyDown", key: "Enter" });
  await cdp("Input.dispatchKeyEvent", { type: "keyUp", key: "Enter" });
  await waitFor(`groupedView.shadowRoot.querySelectorAll('.star').length === 3`);
  assert.equal(await evaluate(`groupedView.scene.nodes.length`), 3, 'canonical scene remains at project level');
  await evaluate(`groupedView.selectNode('example/compiler',{focus:false})`);
  assert.ok(await evaluate(`Boolean(groupedView.shadowRoot.querySelector('[data-semantic-collapse]'))`));
  await evaluate(`groupedView.shadowRoot.querySelector('[data-semantic-collapse]').click()`);
  await waitFor(`Boolean(groupedView.shadowRoot.querySelector('.star[data-repo="group:user:sample-family"]'))`);
  await evaluate(`window.lazyView = document.createElement('constellation-view'); lazyView.setAttribute('loading','lazy'); lazyView.style.display='none'; lazyView.scene=document.querySelector('#view').scene; document.body.append(lazyView);`);
  assert.equal(await evaluate(`lazyView.shadowRoot.querySelector('main')`), null);
  await evaluate(`lazyView.style.display='block'; lazyView.scrollIntoView()`);
  await waitFor(`Boolean(lazyView.shadowRoot.querySelector('main')?.constellation)`);
  await evaluate(`window.originalFetch = window.fetch; window.cancelledLoads = 0; window.fetch = (url, options) => {
    if (String(url).includes('/slow-scene')) return new Promise((resolve,reject) => options.signal.addEventListener('abort', () => { cancelledLoads++; reject(new DOMException('Aborted','AbortError')); }));
    if (String(url).includes('/fixture-scene')) return Promise.resolve(new Response(JSON.stringify(document.querySelector('#view').scene)));
    return originalFetch(url,options);
  }; lazyView.setAttribute('src','/slow-scene'); lazyView.setAttribute('src','/fixture-scene');`);
  await waitFor(`lazyView.cacheStatistics.sources === 1`);
  assert.equal(await evaluate('cancelledLoads'), 1);
  await evaluate(`lazyView.setAttribute('src','/slow-scene'); lazyView.remove();`);
  assert.equal(await evaluate('cancelledLoads'), 2);
  await evaluate(`lazyView.removeAttribute('src'); document.body.append(lazyView); lazyView.scrollIntoView()`);
  await waitFor(`Boolean(lazyView.shadowRoot.querySelector('main')?.constellation)`);
  assert.equal(await evaluate('lazyView.cacheStatistics.pipeline.entries'), 0);
  await evaluate('window.fetch = originalFetch');
  assert.deepEqual(errors, []);
});
