import { username } from './constellation.mjs';

export const projectUrl = 'https://github.com/mnichols08/constellation';

export function installationLinks(repository, workflow) {
  const target = repository.trim();
  if (!/^[a-z\d][a-z\d-]*\/[a-z\d_.-]+$/i.test(target) || ['.', '..'].includes(target.split('/')[1])) throw new Error('Enter the workflow repository as owner/repository.');
  const [owner, repo] = target.split('/');
  const base = `https://github.com/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`;
  const install = new URL(`${base}/new/HEAD`);
  install.searchParams.set('filename', '.github/workflows/constellation.yml');
  install.searchParams.set('value', workflow);
  const create = new URL('https://github.com/new');
  create.searchParams.set('name', repo);
  create.searchParams.set('visibility', 'public');
  create.searchParams.set('readme', '1');
  return {
    // Large custom CSS can exceed browser/server URL limits. Keep copy/download available.
    install: install.href.length <= 8000 ? install.href : null,
    create: create.href,
    actions: `${base}/actions/workflows/constellation.yml`,
  };
}

export function readmeSnippet(account, repository) {
  const name = account ? username(account) : 'My';
  const target = repository?.trim() || (account ? `${username(account)}/${username(account)}` : 'YOUR_USERNAME/YOUR_REPOSITORY');
  if (!/^[a-z\d][a-z\d-]*\/[a-z\d_.-]+$/i.test(target) && target !== 'YOUR_USERNAME/YOUR_REPOSITORY') throw new Error('Enter the workflow repository as owner/repository.');
  const path = target.split('/').map(encodeURIComponent).join('/');
  const image = `https://raw.githubusercontent.com/${path}/output/constellation.svg`;
  return `[![${name} GitHub constellation](${image})](${projectUrl})\n\nMade with [GitHub Constellation](${projectUrl}) by [@mnichols08](https://github.com/mnichols08).`;
}

export function renderWorkflow(_account, options) {
  const { activityData, codingRhythmData, historyData, accountData, organizationData, ...configuration } = options;
  // JSON escapes preserve literal CSS dollars while preventing GitHub Actions
  // from interpreting user-authored CSS as workflow expressions.
  const json = JSON.stringify({ ...configuration, version: 6 }, null, 2).replace(/\$/g, '\\u0024');
  const config = json.split('\n').map(line => `            ${line}`).join('\n');
  return `# Save as .github/workflows/constellation.yml
# Generated by GitHub Constellation. Settings and CSS match the preview.
name: Daily constellation
on:
  schedule:
    - cron: '17 6 * * *'
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: constellation-output
  cancel-in-progress: false
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mnichols08/constellation@v2
        with:
          publish: 'true'${options.accountData?.type === 'Organization' || options.accountType === 'organization' || options.organizationUser ? `\n          username: '${username(_account)}'` : ''}
          config-json: |
${config}
`;
}
