import { username } from './constellation.mjs';

export const projectUrl = 'https://github.com/mnichols08/github-constellation';

export function readmeSnippet(account) {
  const name = account ? username(account) : 'My';
  return `[![${name} GitHub constellation](./dist/constellation.svg)](${projectUrl})\n\nMade with [GitHub Constellation](${projectUrl}) by [@mnichols08](https://github.com/mnichols08).`;
}

export function renderWorkflow(account, options) {
  // JSON escapes preserve literal CSS dollars while preventing GitHub Actions
  // from interpreting user-authored CSS as workflow expressions.
  const json = JSON.stringify(options, null, 2).replace(/\$/g, '\\u0024');
  const config = json.split('\n').map(line => `            ${line}`).join('\n');
  const owner = account ? username(account) : '${{ github.repository_owner }}';
  return `# Save as .github/workflows/constellation.yml
# Generated by GitHub Constellation. Settings and CSS match the preview.
name: Daily constellation
on:
  schedule:
    - cron: '17 6 * * *'
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: constellation-\${{ github.ref }}
  cancel-in-progress: false
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mnichols08/github-constellation@main
        with:
          username: '${owner}'
          token: \${{ secrets.GITHUB_TOKEN }}
          output: dist/constellation.svg
          config-json: |
${config}
      - name: Save constellation
        shell: bash
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -- dist/constellation.svg
          if ! git diff --cached --quiet; then
            git commit -m 'Update GitHub constellation'
            git push
          fi
`;
}
