import { username } from './constellation.mjs';

export const projectUrl = 'https://github.com/mnichols08/constellation';

export function readmeSnippet(account, repository) {
  const name = account ? username(account) : 'My';
  const target = repository?.trim() || (account ? `${username(account)}/${username(account)}` : 'YOUR_USERNAME/YOUR_REPOSITORY');
  if (!/^[a-z\d][a-z\d-]*\/[a-z\d_.-]+$/i.test(target) && target !== 'YOUR_USERNAME/YOUR_REPOSITORY') throw new Error('Enter the workflow repository as owner/repository.');
  const path = target.split('/').map(encodeURIComponent).join('/');
  const image = `https://raw.githubusercontent.com/${path}/output/constellation.svg`;
  return `[![${name} GitHub constellation](${image})](https://github.com/${path}/blob/output/constellation.svg)\n\nMade with [GitHub Constellation](${projectUrl}) by [@mnichols08](https://github.com/mnichols08).`;
}

export function renderWorkflow(_account, options) {
  // JSON escapes preserve literal CSS dollars while preventing GitHub Actions
  // from interpreting user-authored CSS as workflow expressions.
  const json = JSON.stringify(options, null, 2).replace(/\$/g, '\\u0024');
  const config = json.split('\n').map(line => `            ${line}`).join('\n');
  return `# Save as .github/workflows/constellation.yml
# Generated by GitHub Constellation. Settings and CSS match the preview.
name: Daily constellation
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: constellation-output
  cancel-in-progress: false
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mnichols08/constellation@main
        with:
          username: \${{ github.repository_owner }}
          token: \${{ secrets.GITHUB_TOKEN }}
          output: constellation.svg
          publish: 'true'
          output-branch: output
          config-json: |
${config}
`;
}
